//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.DAlquiler = new HashSet<DAlquiler>();
        }
    
        public int ID_LIBRO { get; set; }
        public Nullable<int> PUBLICADO { get; set; }
        public string ESTADO_LIBRO { get; set; }
        public string TITULO_LIBRO { get; set; }
        public string CONTENIDO { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> ID_EDITORIAL_LIBRO { get; set; }
        public Nullable<int> ID_AUTOR_LIBRO { get; set; }
    
        public virtual Autor Autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAlquiler> DAlquiler { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
